name = "ViewerGL"
uuid = "32496ab8-9004-11e9-0205-c9e71bda7ab0"
authors = ["apaoluzzi <apaoluzzi@mac.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearAlgebraicRepresentation = "95167b0c-186a-594b-a231-52369c6de044"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
QHull = "a8468747-bd6f-53ef-9e5c-744dbc5c59e7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
GLFW = "^3.0.0"
LinearAlgebraicRepresentation = "^1.0.0"
ModernGL = "^1.0.0"
QHull = "^0.1.2"
julia = "^1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
